handlers = java.util.logging.ConsoleHandler
.level = FINEST
java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
org.jline.level = FINEST
org.jline.terminal.level = FINEST
org.jline.terminal.spi.level = FINEST
org.jline.terminal.impl.level = FINEST
org.jline.terminal.impl.jna.level = FINEST
org.jline.terminal.impl.jni.level = FINEST
org.jline.terminal.impl.ffm.level = FINEST
org.jline.terminal.impl.jansi.level = FINEST
org.jline.terminal.impl.console.level = FINEST