package com.lifeforge.model;

/**
 * Deterministic match score and breakdown for LIFEForge recommendations:
 *
 * Match Score =
 *     Profile Completeness × 40%
 *   + Goal Alignment × 40%
 *   + Activity Synergy × 20%
 *
 * This score is explainable, transparent, and reproducible. It is NOT
 * generated by AI.
 */
public class MatchScoreBreakdown {

    private final double profileCompleteness;
    private final double goalAlignment;
    private final double activitySynergy;
    private final int totalScore;
    private final String progressBar;
    private final String mismatchWarning;
    private final GoalCompatibilityStatus compatibilityStatus;

    public MatchScoreBreakdown(double profileCompleteness, double goalAlignment, double activitySynergy) {
        this(profileCompleteness, goalAlignment, activitySynergy, null, null);
    }

    public MatchScoreBreakdown(double profileCompleteness, double goalAlignment, double activitySynergy, String mismatchWarning) {
        this(profileCompleteness, goalAlignment, activitySynergy, mismatchWarning, null);
    }

    public MatchScoreBreakdown(double profileCompleteness, double goalAlignment, double activitySynergy, String mismatchWarning, GoalCompatibilityStatus compatibilityStatus) {
        this.profileCompleteness = Math.max(0.0, Math.min(100.0, profileCompleteness));
        this.goalAlignment = Math.max(0.0, Math.min(100.0, goalAlignment));
        this.activitySynergy = Math.max(0.0, Math.min(100.0, activitySynergy));
        this.mismatchWarning = mismatchWarning;
        this.compatibilityStatus = compatibilityStatus;

        double weighted = (this.profileCompleteness * 0.40)
                + (this.goalAlignment * 0.40)
                + (this.activitySynergy * 0.20);
        this.totalScore = (int) Math.round(weighted);
        this.progressBar = buildProgressBar(this.totalScore);
    }

    public static MatchScoreBreakdown compute(User user, Goal goal, boolean hasGoalRecommendations, boolean hasActivitySpecificRec) {
        double profileComp = computeProfileCompleteness(user);
        double goalAlign = computeGoalAlignment(user, goal, hasGoalRecommendations, hasActivitySpecificRec);
        double actSynergy = computeActivitySynergy(user, goal, hasActivitySpecificRec);
        String warning = computeMismatchWarning(user, goal, goalAlign);
        GoalCompatibilityStatus compStatus = GoalCompatibilityStatus.compute(user, goal);

        return new MatchScoreBreakdown(profileComp, goalAlign, actSynergy, warning, compStatus);
    }

    /**
     * Profile Completeness (40% weight):
     * Evaluates whether the 5 core profile fields (Age, Gender, Height, Weight, Activity Level)
     * are populated with valid values (20% each).
     */
    public static double computeProfileCompleteness(User user) {
        if (user == null) {
            return 0.0;
        }
        int filled = 0;
        if (user.getAge() != null && user.getAge() > 0) filled++;
        if (user.getGender() != null) filled++;
        if (user.getHeightCm() != null && user.getHeightCm() > 0) filled++;
        if (user.getWeightKg() != null && user.getWeightKg() > 0) filled++;
        if (user.getActivityLevel() != null) filled++;

        return (filled / 5.0) * 100.0;
    }

    /**
     * Goal Alignment (40% weight):
     * Evaluates how appropriate the selected goal is given the user's actual physical profile context
     * (height, weight, BMI context, and catalog support).
     * Handled continuously across underweight-like, healthy normal, overweight, and higher-weight contexts.
     * Guidance-only metric; does not diagnose medical conditions.
     */
    public static double computeGoalAlignment(User user, Goal goal, boolean hasGoalRecommendations, boolean hasActivitySpecificRec) {
        if (goal == null) {
            return 0.0;
        }
        if (user == null) {
            return hasGoalRecommendations ? 70.0 : 40.0;
        }

        double height = user.getHeightCm() != null ? user.getHeightCm() : 0.0;
        double weight = user.getWeightKg() != null ? user.getWeightKg() : 0.0;
        String goalCode = goal.getCode() != null ? goal.getCode().toUpperCase(java.util.Locale.ROOT) : "";

        // Missing height/weight falls back to baseline catalog readiness
        if (height <= 0.0 || weight <= 0.0) {
            return hasGoalRecommendations ? 75.0 : 50.0;
        }

        double heightM = height / 100.0;
        double bmi = weight / (heightM * heightM);

        double baseAlignment;

        if (goalCode.contains("GAIN") && goalCode.contains("WEIGHT")) {
            // GAIN_WEIGHT:
            // Underweight context (BMI < 18.5): optimal alignment (90% - 98%)
            // Lean / lower-normal (18.5 <= BMI < 21.0): strong alignment (80% - 90%)
            // Mid-normal (21.0 <= BMI < 23.5): moderate alignment (60% - 80%)
            // Upper-normal (23.5 <= BMI <= 25.0): moderate-low (40% - 60%)
            // Overweight (25.0 < BMI <= 30.0): low alignment (15% - 40%)
            // Higher-weight (BMI > 30.0): severe mismatch (< 15% down to 2%)
            if (bmi <= 16.0) {
                baseAlignment = Math.min(98.0, 95.0 + (16.0 - Math.max(10.0, bmi)) * 0.5);
            } else if (bmi <= 18.5) {
                baseAlignment = 90.0 + ((18.5 - bmi) / 2.5) * 5.0;
            } else if (bmi <= 21.0) {
                baseAlignment = 80.0 + ((21.0 - bmi) / 2.5) * 10.0;
            } else if (bmi <= 23.5) {
                baseAlignment = 60.0 + ((23.5 - bmi) / 2.5) * 20.0;
            } else if (bmi <= 25.0) {
                baseAlignment = 40.0 + ((25.0 - bmi) / 1.5) * 20.0;
            } else if (bmi <= 30.0) {
                baseAlignment = 15.0 + ((30.0 - bmi) / 5.0) * 25.0;
            } else {
                baseAlignment = Math.max(2.0, 15.0 - (bmi - 30.0) * 1.6);
            }
        } else if (goalCode.contains("LOSE") || (goalCode.contains("WEIGHT") && !goalCode.contains("GAIN"))) {
            // LOSE_WEIGHT:
            // Higher-weight (BMI >= 30.0): optimal alignment (95% - 98%)
            // Overweight (25.0 <= BMI < 30.0): very high alignment (85% - 95%)
            // Healthy normal (21.0 <= BMI < 25.0): moderate alignment (60% - 85%)
            // Lean / lower-normal (18.5 <= BMI < 21.0): lower alignment (30% - 60%)
            // Underweight-like (BMI < 18.5): severe mismatch (< 30% down to 2%)
            if (bmi >= 30.0) {
                baseAlignment = Math.min(98.0, 95.0 + Math.min(3.0, (bmi - 30.0) * 0.5));
            } else if (bmi >= 25.0) {
                baseAlignment = 85.0 + ((bmi - 25.0) / 5.0) * 10.0;
            } else if (bmi >= 21.0) {
                baseAlignment = 60.0 + ((bmi - 21.0) / 4.0) * 25.0;
            } else if (bmi >= 18.5) {
                baseAlignment = 30.0 + ((bmi - 18.5) / 2.5) * 30.0;
            } else {
                baseAlignment = Math.max(2.0, 30.0 - (18.5 - bmi) * 4.0);
            }
        } else if (goalCode.contains("MUSCLE")) {
            // BUILD_MUSCLE:
            // Optimal in healthy normal to athletic range (20.0 <= BMI <= 26.0): 92% - 96%
            // Lean (18.0 <= BMI < 20.0): 82% - 92%
            // Overweight (26.0 < BMI <= 30.0): 80% - 92% (body recomposition)
            // Higher weight (BMI > 30.0): 40% - 80%
            // Severely underweight (BMI < 18.0): 40% - 82%
            if (bmi >= 20.0 && bmi <= 26.0) {
                baseAlignment = 92.0 + Math.sin((bmi - 20.0) / 6.0 * Math.PI) * 4.0;
            } else if (bmi > 26.0 && bmi <= 30.0) {
                baseAlignment = 80.0 + ((30.0 - bmi) / 4.0) * 12.0;
            } else if (bmi > 30.0) {
                baseAlignment = Math.max(40.0, 80.0 - (bmi - 30.0) * 3.0);
            } else if (bmi >= 18.0) {
                baseAlignment = 82.0 + ((bmi - 18.0) / 2.0) * 10.0;
            } else {
                baseAlignment = Math.max(40.0, 82.0 - (18.0 - bmi) * 8.0);
            }
        } else if (goalCode.contains("FITNESS")) {
            // IMPROVE_FITNESS:
            // Universally positive alignment across healthy ranges: 88% - 95%
            if (bmi >= 18.5 && bmi <= 27.0) {
                baseAlignment = 92.0 + Math.sin((bmi - 18.5) / 8.5 * Math.PI) * 3.0;
            } else if (bmi > 27.0) {
                baseAlignment = Math.max(70.0, 92.0 - (bmi - 27.0) * 2.0);
            } else {
                baseAlignment = Math.max(70.0, 92.0 - (18.5 - bmi) * 2.5);
            }
        } else if (goalCode.contains("SLEEP")) {
            // IMPROVE_SLEEP:
            baseAlignment = 90.0;
            if (user.getAge() != null && user.getAge() >= 40) {
                baseAlignment += Math.min(3.0, (user.getAge() - 40) * 0.1);
            }
        } else if (goalCode.contains("SKIN")) {
            // IMPROVE_SKIN_HEALTH:
            baseAlignment = 90.0;
        } else {
            // GENERAL_WELLNESS or other:
            baseAlignment = 90.0;
        }

        if (!hasGoalRecommendations) {
            baseAlignment *= 0.80;
        }
        if (hasActivitySpecificRec && baseAlignment >= 50.0) {
            baseAlignment = Math.min(100.0, baseAlignment + 2.0);
        }

        return Math.max(0.0, Math.min(100.0, Math.round(baseAlignment * 10.0) / 10.0));
    }

    /**
     * Activity Synergy (20% weight):
     * Evaluates the synergy between the user's current Activity Level and the selected goal.
     * Sedentary, Lightly Active, Moderately Active, and Very Active users receive distinct,
     * calibrated scores.
     */
    public static double computeActivitySynergy(User user, Goal goal, boolean hasActivitySpecificRec) {
        if (user == null || user.getActivityLevel() == null) {
            return 50.0;
        }

        ActivityLevel act = user.getActivityLevel();
        String goalCode = goal != null && goal.getCode() != null
                ? goal.getCode().toUpperCase(java.util.Locale.ROOT)
                : "";

        double synergy;

        if (goalCode.contains("BUILD_MUSCLE") || goalCode.contains("MUSCLE")) {
            synergy = switch (act) {
                case SEDENTARY -> 40.0;
                case LIGHTLY_ACTIVE -> 65.0;
                case MODERATELY_ACTIVE -> 90.0;
                case VERY_ACTIVE -> 95.0;
                case EXTRA_ACTIVE -> 90.0;
            };
        } else if (goalCode.contains("GAIN_WEIGHT") || (goalCode.contains("GAIN") && goalCode.contains("WEIGHT"))) {
            synergy = switch (act) {
                case SEDENTARY -> 40.0;
                case LIGHTLY_ACTIVE -> 65.0;
                case MODERATELY_ACTIVE -> 90.0;
                case VERY_ACTIVE -> 85.0;
                case EXTRA_ACTIVE -> 75.0;
            };
        } else if (goalCode.contains("LOSE_WEIGHT") || (goalCode.contains("LOSE") && goalCode.contains("WEIGHT"))) {
            synergy = switch (act) {
                case SEDENTARY -> 50.0;
                case LIGHTLY_ACTIVE -> 70.0;
                case MODERATELY_ACTIVE -> 95.0;
                case VERY_ACTIVE -> 90.0;
                case EXTRA_ACTIVE -> 82.0;
            };
        } else if (goalCode.contains("FITNESS")) {
            synergy = switch (act) {
                case SEDENTARY -> 50.0;
                case LIGHTLY_ACTIVE -> 72.0;
                case MODERATELY_ACTIVE -> 95.0;
                case VERY_ACTIVE -> 92.0;
                case EXTRA_ACTIVE -> 88.0;
            };
        } else if (goalCode.contains("SLEEP")) {
            synergy = switch (act) {
                case SEDENTARY -> 60.0;
                case LIGHTLY_ACTIVE -> 80.0;
                case MODERATELY_ACTIVE -> 95.0;
                case VERY_ACTIVE -> 85.0;
                case EXTRA_ACTIVE -> 75.0;
            };
        } else if (goalCode.contains("SKIN")) {
            synergy = switch (act) {
                case SEDENTARY -> 65.0;
                case LIGHTLY_ACTIVE -> 80.0;
                case MODERATELY_ACTIVE -> 92.0;
                case VERY_ACTIVE -> 85.0;
                case EXTRA_ACTIVE -> 80.0;
            };
        } else {
            // General wellness / other:
            synergy = switch (act) {
                case SEDENTARY -> 60.0;
                case LIGHTLY_ACTIVE -> 80.0;
                case MODERATELY_ACTIVE -> 95.0;
                case VERY_ACTIVE -> 88.0;
                case EXTRA_ACTIVE -> 82.0;
            };
        }

        if (hasActivitySpecificRec) {
            synergy = Math.min(100.0, synergy + 3.0);
        }

        return Math.max(0.0, Math.min(100.0, Math.round(synergy * 10.0) / 10.0));
    }

    /**
     * Evaluates whether there is a low profile-goal alignment and produces an actionable,
     * non-diagnostic guidance warning.
     */
    public static String computeMismatchWarning(User user, Goal goal, double goalAlignment) {
        if (goalAlignment >= 50.0 || goal == null || user == null) {
            return null;
        }

        double height = user.getHeightCm() != null ? user.getHeightCm() : 0.0;
        double weight = user.getWeightKg() != null ? user.getWeightKg() : 0.0;
        if (height <= 0.0 || weight <= 0.0) {
            return null;
        }

        double bmi = weight / ((height / 100.0) * (height / 100.0));
        String goalCode = goal.getCode() != null ? goal.getCode().toUpperCase(java.util.Locale.ROOT) : "";
        String goalName = goal.getName() != null ? goal.getName() : "selected goal";

        if (goalCode.contains("GAIN") && goalCode.contains("WEIGHT") && bmi >= 25.0) {
            return String.format(
                    "Profile context indicates a higher-weight range (BMI %.1f). A '%s' goal may not align with healthy weight management; consider 'Lose Weight' or 'Improve Fitness'.",
                    bmi, goalName);
        } else if (goalCode.contains("LOSE") && bmi < 18.5) {
            return String.format(
                    "Profile context indicates a lower-weight range (BMI %.1f). A '%s' goal is not aligned with healthy weight maintenance; consider 'Gain Weight' or 'Improve Fitness'.",
                    bmi, goalName);
        } else {
            return String.format(
                    "Profile context indicates low alignment (%.0f%%) with the '%s' goal. Consider reviewing your goal selection.",
                    goalAlignment, goalName);
        }
    }

    public boolean hasMismatchWarning() {
        return mismatchWarning != null && !mismatchWarning.isBlank();
    }

    public String getMismatchWarning() {
        return mismatchWarning != null ? mismatchWarning : "";
    }

    private static String buildProgressBar(int score) {
        int totalBlocks = 20;
        int filled = (int) Math.round((Math.max(0, Math.min(100, score)) / 100.0) * totalBlocks);
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        for (int i = 0; i < filled; i++) {
            sb.append("█");
        }
        for (int i = filled; i < totalBlocks; i++) {
            sb.append("░");
        }
        sb.append("] ").append(score).append("%");
        return sb.toString();
    }

    public double getProfileCompleteness() {
        return profileCompleteness;
    }

    public double getGoalAlignment() {
        return goalAlignment;
    }

    public double getActivitySynergy() {
        return activitySynergy;
    }

    public double getProfileCompletenessContribution() {
        return profileCompleteness * 0.40;
    }

    public double getGoalAlignmentContribution() {
        return goalAlignment * 0.40;
    }

    public double getActivitySynergyContribution() {
        return activitySynergy * 0.20;
    }

    public int getTotalScore() {
        return totalScore;
    }

    public String getProgressBar() {
        return progressBar;
    }

    public GoalCompatibilityStatus getCompatibilityStatus() {
        return compatibilityStatus;
    }
}
